<div style="float: right; width: 50%;">
    <p style="margin: 0; text-align:right;">Python en Ciencia de Datos Aplicada</p>
    <p style="margin: 0; text-align:right; padding-button: 100px;">Prácticas - Afianzando conceptos</p>
</div>

</div>
<div style="width: 100%; clear: both;">
<div style="width:100%;">&nbsp;</div>

In [1]:
%load_ext pycodestyle_magic

In [2]:
# Activem les alertes d'estil
%pycodestyle_on

# Prácticas - Afianzando conceptos


## Ejercicio 1

Los siguientes ejercios se realizarán utilizando el dataset `sales-data.csv` que contiene la información sobre diversas órdenes. Cada fila representa una orden. Este dataset se ha limpiado con tal de que sea más fácil manipularlo, parte de un dataset original que se puede encontrat en la [siguiente URL](https://www.kaggle.com/kyanyoga/sample-sales-data).

Los campos del dataset son:

- ORDERID: ID de la orden.
- ORDERPRICE: Precio total de la orden.
- ORDERDATE: Fecha en la que se realizó la orden.
- STATUS: Estado de la orden (Enviada, no enviada, etc.).
- PRODUCTLINE: Tipo de producto.
- PRODUCTCODE: Código de producto.
- CUSTOMERNAME: Nombre del cliente.
- CITY: Ciudad a la que se envía la orden.
- COUNTRY: País al que se envía la orden.

1. Cargad el dataset y mostrad por pantalla los 10 últimos elementos.

2. De estos 10 últimos elementos del punto 1, mostrad los 5 primeros.

In [3]:
# Respuesta 1.1
import pandas as pd

sales_data = pd.read_csv("data/sales-data.csv")
print(sales_data.tail(10))

     ORDERID  ORDERPRICE       ORDERDATE   STATUS   PRODUCTLINE PRODUCTCODE  \
297    10387     4175.60   3/2/2005 0:00  Shipped   Motorcycles    S32_1374   
298    10364     2317.44   1/6/2005 0:00  Shipped   Motorcycles    S32_2206   
299    10116     1711.26  4/11/2003 0:00  Shipped        Trains    S32_3207   
300    10144     1637.20  8/13/2003 0:00  Shipped  Vintage Cars    S32_4289   
301    10156      820.40  10/8/2003 0:00  Shipped  Vintage Cars    S50_1341   
302    10199     1113.60  12/1/2003 0:00  Shipped  Vintage Cars    S50_1341   
303    10397     2577.60  3/28/2005 0:00  Shipped         Ships   S700_1938   
304    10352     2352.67  12/3/2004 0:00  Shipped         Ships   S700_2047   
305    10118     4219.20  4/21/2003 0:00  Shipped         Ships   S700_3505   
306    10294     4692.60  9/10/2004 0:00  Shipped         Ships   S700_3962   

                    CUSTOMERNAME        CITY    COUNTRY  
297      Dragon Souveniers, Ltd.   Singapore  Singapore  
298         Ma

In [4]:
# Respuesta 1.2
print(sales_data.tail(10).head(5))

     ORDERID  ORDERPRICE       ORDERDATE   STATUS   PRODUCTLINE PRODUCTCODE  \
297    10387     4175.60   3/2/2005 0:00  Shipped   Motorcycles    S32_1374   
298    10364     2317.44   1/6/2005 0:00  Shipped   Motorcycles    S32_2206   
299    10116     1711.26  4/11/2003 0:00  Shipped        Trains    S32_3207   
300    10144     1637.20  8/13/2003 0:00  Shipped  Vintage Cars    S32_4289   
301    10156      820.40  10/8/2003 0:00  Shipped  Vintage Cars    S50_1341   

                CUSTOMERNAME       CITY    COUNTRY  
297  Dragon Souveniers, Ltd.  Singapore  Singapore  
298     Marseille Mini Autos  Marseille     France  
299             Royale Belge  Charleroi    Belgium  
300             Royale Belge  Charleroi    Belgium  
301    Euro Shopping Channel     Madrid      Spain  


## Ejercicio 2

Partiendo del dataset anterior:

1. Cread y mostrad, utilizando la estructura de datos más adecuada (justificad el motivo), todas las ciudades que aparecen en el dataset. Sólo queremos que las ciudades aparezcan una vez (las ciudades NO pueden estar repetidas). 

2. Cread una lista con las ciudades del punto 1 ordenadas lexicográficamente.

Partiendo de la lista creada en el punto 2 y haciendo uso del _**list slicing**_:

3. Cread y mostrad una lista de ciudades en orden lexicográfico inverso.

4. Cread y mostrad una lista de las posiciones pares. 

Partiendo de la lista creada en el punto 2 y haciendo uso de las _**list comprehensions**_:

5. Cread y mostrad una lista de ciudades con nombre de longitud impar.

6. Cread y mostrad una lista de ciudades que empiezan por vocal.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">NM</span> **(1 punto)**

In [5]:
# Respuesta 2.1

cities = set(sales_data["CITY"])
print(cities)

# Un conjunto es una estructura de datos adecuada, ya que no queremos
# elementos repetidos y no hay condiciones con respecto al orden
# en el cual se han de guardar las ciudades.

{'Liverpool', 'Bruxelles', 'Frankfurt', 'Nashua', 'White Plains', 'Paris', 'Melbourne', 'San Rafael', 'Reims', 'Munich', 'Cambridge', 'Glen Waverly', 'Allentown', 'New Bedford', 'Chatswood', 'San Francisco', 'South Brisbane', 'Newark', 'Bergen', 'Vancouver', 'Graz', 'Bergamo', 'Dublin', 'Los Angeles', 'Salzburg', 'Las Vegas', 'Stavern', 'London', 'Aaarhus', 'Glendale', 'Charleroi', 'Lule', 'San Jose', 'Koln', 'Nantes', 'Versailles', 'San Diego', 'Brisbane', 'Oslo', 'Sevilla', 'Manchester', 'Burlingame', 'Torino', 'Pasadena', 'Barcelona', 'Madrid', 'Lille', 'Minato-ku', 'North Sydney', 'New Haven', 'Burbank', 'Bridgewater', 'Boston', 'Cowes', 'Osaka', 'Helsinki', 'Philadelphia', 'Tsawassen', 'Gensve', 'Kobenhavn', 'Strasbourg', 'Makati City', 'Montreal', 'NYC', 'Oulu', 'Marseille', 'Espoo', 'Toulouse', 'Brickhaven', 'Boras', 'Reggio Emilia', 'Singapore', 'Lyon'}


In [6]:
# Respuesta 2.2

cities_sorted = sorted(cities)

In [7]:
# Respuesta 2.3

cities_inverted = cities_sorted[::-1]

print(cities_inverted)

['White Plains', 'Versailles', 'Vancouver', 'Tsawassen', 'Toulouse', 'Torino', 'Strasbourg', 'Stavern', 'South Brisbane', 'Singapore', 'Sevilla', 'San Rafael', 'San Jose', 'San Francisco', 'San Diego', 'Salzburg', 'Reims', 'Reggio Emilia', 'Philadelphia', 'Pasadena', 'Paris', 'Oulu', 'Oslo', 'Osaka', 'North Sydney', 'Newark', 'New Haven', 'New Bedford', 'Nashua', 'Nantes', 'NYC', 'Munich', 'Montreal', 'Minato-ku', 'Melbourne', 'Marseille', 'Manchester', 'Makati City', 'Madrid', 'Lyon', 'Lule', 'Los Angeles', 'London', 'Liverpool', 'Lille', 'Las Vegas', 'Koln', 'Kobenhavn', 'Helsinki', 'Graz', 'Glendale', 'Glen Waverly', 'Gensve', 'Frankfurt', 'Espoo', 'Dublin', 'Cowes', 'Chatswood', 'Charleroi', 'Cambridge', 'Burlingame', 'Burbank', 'Bruxelles', 'Brisbane', 'Bridgewater', 'Brickhaven', 'Boston', 'Boras', 'Bergen', 'Bergamo', 'Barcelona', 'Allentown', 'Aaarhus']


In [8]:
# Respuesta 2.4

even_positions_cities = cities_sorted[::2]

print(even_positions_cities)

['Aaarhus', 'Barcelona', 'Bergen', 'Boston', 'Bridgewater', 'Bruxelles', 'Burlingame', 'Charleroi', 'Cowes', 'Espoo', 'Gensve', 'Glendale', 'Helsinki', 'Koln', 'Lille', 'London', 'Lule', 'Madrid', 'Manchester', 'Melbourne', 'Montreal', 'NYC', 'Nashua', 'New Haven', 'North Sydney', 'Oslo', 'Paris', 'Philadelphia', 'Reims', 'San Diego', 'San Jose', 'Sevilla', 'South Brisbane', 'Strasbourg', 'Toulouse', 'Vancouver', 'White Plains']


In [9]:
# Respuesta 2.5

cities_odd_length = [city for city in cities_sorted if len(city) % 2 != 0]

print(cities_odd_length)

['Aaarhus', 'Allentown', 'Barcelona', 'Bergamo', 'Boras', 'Bridgewater', 'Bruxelles', 'Burbank', 'Cambridge', 'Charleroi', 'Chatswood', 'Cowes', 'Espoo', 'Frankfurt', 'Kobenhavn', 'Las Vegas', 'Lille', 'Liverpool', 'Los Angeles', 'Makati City', 'Marseille', 'Melbourne', 'Minato-ku', 'NYC', 'New Bedford', 'New Haven', 'Osaka', 'Paris', 'Reggio Emilia', 'Reims', 'San Diego', 'San Francisco', 'Sevilla', 'Singapore', 'Stavern', 'Tsawassen', 'Vancouver']


In [10]:
# Respuesta 2.6
import re

cities_vowel = [
    city_vowel
    for city_vowel in cities_sorted
    if re.match(r"^[AEIOUaeiou]", city_vowel)]

# Respuesta sin hacer uso de regex
# cities_vowel = [city_vowel for city_vowel in cities_sorted
#                   if city_vowel[0] in 'AEIOUaeiou']

print(cities_vowel)

['Aaarhus', 'Allentown', 'Espoo', 'Osaka', 'Oslo', 'Oulu']


## Ejercicio 3

Disponemos de un almacén donde se van guardando las órdenes ya preparadas en cajas, mientras esperan que sean recogidas por el camión que las trasladará a las ciudades de destino. El almacén tiene una única puerta, a través de la cual se entran las órdenes cuando están preparadas y salen cuando hace falta cargar el camión. Podemos asumir que todas las órdenes se empaquetan en una caja cuadrada de la misma medida, y que no es posible pasar una caja por encima de otra.

El almacén tiene la siguiente forma:

<img src="figs/magatzem_1.png" width=100 height=80 />

1. ¿Qué estructura de datos sería la más conveniente para representar las cajas que se encuentran en el almacén?.

2. Si se han guardado en el almacén las órdenes 10387, 10364, 10116, 10144 y 10156 (en este orden) y un camión con capacidad para 3 órdenes ya ha venido a cargar y se ha ido completamente lleno, ¿ qué órdenes quedan guardadas en el almacén? Reproducid el proceso utilizando la estructura de datos que habéis indicado en el apartado 1.

3. El negocio funciona muy bien y se decide ampliar el almacén con el espacio de una nave colindante, de manera que ahora se pueden guardar el doble de cajas. El nuevo almacén sigue teniendo una única puerta, y queda de la siguiente manera:

<img src="figs/magatzem_2.png" width=100 height=80 />

¿Es necesario actualizar la estructura de datos que representaba las cajas del almacén? Justificad la respuesta.

**Nota**: Para las ilustraciones de los alamacenes se han utilizado las imágenes originales [1](https://www.freevector.com/arrow-stickers#) y [2](https://www.freevector.com/carton-box-on-yellow-vector-26711).

`Respuesta 3.1 : Podriamos utilizar una pila (stack) para representar el almacén, ya que la primera caja en entrar siempra será la última en salir (FILO).`

In [11]:
# Respuesta 3.2

def print_stack(s, msg_bef=None, msg_after=None):
    # Definimos la función auxiliar print_stack, que nos
    # permitirá visualizar una pila.
    if msg_bef:
        print(msg_bef)

    if len(s) == 0:
        max_len = 10
    else:
        max_len = max([len(e) for e in s]) + 4

    print("|" + " " * (max_len + 2) + "|")
    for e in s[::-1]:
        print("| " + e + " " * (max_len - len(e)) + " |")
    print("|" + "_" * (max_len + 2) + "|")

    print(msg_after + "\n" if msg_after else "\n")


stack = []

# Añadimos los 5 elementos a la pila en el orden indicado
stack.append("10387")
stack.append("10364")
stack.append("10116")
stack.append("10144")
stack.append("10156")
print_stack(stack, "Almacén inicial (Antes de la recogida del camión)")

# Eliminamos los 3 elementos que se lleva el camión
e1 = stack.pop()
e2 = stack.pop()
e3 = stack.pop()
print_stack(stack, "Almacén final (después de la recogida del camión)")

Almacén inicial (Antes de la recogida del camión)
|           |
| 10156     |
| 10144     |
| 10116     |
| 10364     |
| 10387     |
|___________|


Almacén final (después de la recogida del camión)
|           |
| 10364     |
| 10387     |
|___________|




**Respuesta 3.3 :** `Haría falta modificar la estructura de datos que representa el almacén, ya que ahora en cada momento podemos sacar como mínimo dos cajas (siempre que el almacén tenga como mínimo dos).
Una posible manera de representar el nuevo almacén sería utilizando dos pilas, una para cada columna de cajas. De esta manera, podríamos representar el hecho de que se puede acceder a las dos columnas de cajas de forma independiente:`

In [12]:
stack_left = []
stack_right = []

Así pues, para el siguiente almacén la representación quedaría así:

In [13]:
stack_left.append("1")
stack_left.append("2")
stack_left.append("3")
stack_left.append("4")
stack_right.append("5")
stack_right.append("6")
print_stack(stack_left, "Pila izquierda")
print_stack(stack_right, "Pila derecha")

Pila izquierda
|       |
| 4     |
| 3     |
| 2     |
| 1     |
|_______|


Pila derecha
|       |
| 6     |
| 5     |
|_______|




Ahora bien, si asumimos que también se puden mover cajas de manera lateral, entonces haría falta una representación más rica con tal de saber si una caja es accessible en un momento dado, y para poder eliminar elementos que no estén en el top de la pila.
Una posible representación de la matriz, que indique si en cada posición hay o o no una caja, juntamente con un algoritmo que controle el acceso a las cajas:

In [14]:
import numpy as np

m = np.zeros((4, 2), int)

m[0, 0] = 1
m[1, 0] = 2
m[2, 0] = 3
m[3, 0] = 4
m[0, 1] = 5
m[1, 1] = 6

print(m)

[[1 5]
 [2 6]
 [3 0]
 [4 0]]


## Ejercicio 4

Partiendo del dataset `sales-data.csv`:

1. Cread una lista de todos los años (no repetidos) que una orden ha ido a *France*.

2. Mostrad el último año que una orden ha ido a *France*.

Mostrad el resultado debidamente formateado (utilizando el método `format()`), incluyendo un mensaje explicativo de los valores que enseñáis.

**Nota:** No es necesario ordenar la lista.

In [15]:
# Respuesta 4.1
items_went_france = sales_data[
    (sales_data["STATUS"] == "Shipped") & (sales_data["COUNTRY"] == "France")
]

items_went_france_dates = pd.to_datetime(
    items_went_france["ORDERDATE"], utc=True
)

items_went_france_years = items_went_france_dates.apply(
    lambda datetime: datetime.year
)

items_went_france_years = list(set(items_went_france_years))

print(
    "The years that the items went to France are: {}".format(
        items_went_france_years
    )
)

The years that the items went to France are: [2003, 2004, 2005]


In [16]:
# Respuesta 4.2

print(
    "The last year that an item went to France is: {}".format(
        max(items_went_france_years)
    )
)

# Also valid
print(
    "The last year that an item went to France is: {}".format(
        items_went_france_years[-1]
    )
)

The last year that an item went to France is: 2005
The last year that an item went to France is: 2005


## Ejercicio 5

Partiendo del dataset `sales-data.csv`:

1. Cread una lista con todos los meses (no repetidos) que se envió una orden con 'PRODUCTLINE' del tipo *Motorcycles*.

2. Mostrad el mes que menos *Motorcycles* se enviaron.

3. Mostrad el mes que más *Motorcycles* se enviaron.

Mostrad el resultado debidamente formateado (utilizando el método `format()`), incluyendo un mensaje explicativo de los valores que enseñáis.

In [17]:
# Respuesta 5.1

items_motorcycle = sales_data[
    (sales_data["PRODUCTLINE"] == "Motorcycles") &
    (sales_data["STATUS"] == "Shipped")
]

items_motorcycle_dates = pd.to_datetime(
    items_motorcycle["ORDERDATE"], utc=True
)

items_motorcycle_months = items_motorcycle_dates.apply(
    lambda datetime: datetime.month
)

print(
    "The motorcycles have been sent the following months: {}".format(
        list(set(items_motorcycle_months))
    )
)

# Another option if we consider pairs of month/year
items_motorcycle_months_year = items_motorcycle_dates.apply(
    lambda datetime: f"{datetime.month}/{datetime.year}"
)

print(
    "The motorcycles have been sent the following"
    " pairs of month/year: {}".format(list(set(items_motorcycle_months_year)))
)

The motorcycles have been sent the following months: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
The motorcycles have been sent the following pairs of month/year: ['11/2003', '10/2003', '5/2003', '8/2003', '5/2004', '4/2005', '12/2004', '1/2004', '2/2004', '4/2004', '9/2003', '11/2004', '7/2004', '12/2003', '8/2004', '7/2003', '4/2003', '6/2004', '9/2004', '3/2005', '1/2005', '10/2004', '2/2005', '2/2003']


In [28]:
# Respuesta 5.2
least_motorcycles_shipments = items_motorcycle_months.value_counts().min()

months_least_motorcycles = [
    i
    for i, v in items_motorcycle_months.value_counts().items()
    if v == least_motorcycles_shipments
]

print(
    "The months with least motorcycles shipments are: {}".format(
        months_least_motorcycles
    )
)

# Another option if we consider pairs of month/year

ym_least_motorcycles_shipments = (
    items_motorcycle_months_year.value_counts().min()
)

ym_least_motorcycles = [
    i
    for i, v in items_motorcycle_months_year.value_counts().items()
    if v == ym_least_motorcycles_shipments]

print(
    "The pairs month/year with least motorcycles shipments are: {}".format(
        ym_least_motorcycles
    )
)

The months with least motorcycles shipments are: [3, 5, 6, 7, 12]
The pairs month/year with least motorcycles shipments are: ['12/2003', '4/2003', '5/2003', '8/2003', '5/2004', '7/2003', '2/2003', '9/2003', '12/2004', '7/2004']


In [31]:
# Respuesta 5.3
most_motorcycles_shipments = items_motorcycle_months.value_counts().max()

months_most_motorcycles = [
    i
    for i, v in items_motorcycle_months.value_counts().items()
    if v == most_motorcycles_shipments]

print(
    "The months with most motorcycles shipments are: {}".format(
        months_most_motorcycles
    )
)

# Another option if we consider pairs of month/year
ym_most_motorcycles_shipments = (
    items_motorcycle_months_year.value_counts().max()
)

ym_most_motorcycles = [
    i
    for i, v in items_motorcycle_months_year.value_counts().items()
    if v == ym_most_motorcycles_shipments]

print(
    "The pairs month/year with most motorcycles shipments are: {}".format(
        ym_most_motorcycles
    )
)

The months with most motorcycles shipments are: [11]
The pairs month/year with most motorcycles shipments are: ['11/2004']


## Ejercicio 6

Calculad la diferencia, en días, des de la última orden con destinación **USA** y la primera orden con destinación **Canada**.

Mostrad el resultado debidamente formateado (utilizando el método `format()`), incluyendo un mensaje explicativo de los valores que enseñáis.

In [32]:
# Respuesta 6

from datetime import datetime

USA_data = sales_data[sales_data["COUNTRY"] == "USA"]
USA_data_date = (
    pd.to_datetime(USA_data["ORDERDATE"]).sort_values(ascending=False).iloc[0]
)

canada_data = sales_data[sales_data["COUNTRY"] == "Canada"]
canada_data_date = (
    pd.to_datetime(canada_data["ORDERDATE"]).sort_values().iloc[0]
)

delta = USA_data_date - canada_data_date

print("The difference in days is: {}".format(delta.days))

The difference in days is: 572


## Ejercicio 7

Haciendo uso de las **expresiones regulares** y partiendo del dataset `sales-data.csv`:

1. Encontrad todas las empresas (no repetidas) que contengan en su nombre la abreviatura "Ltd".

2. Encontrad todas las empresas que la string de su nombre empieza y acaba por vocal.

**Nota**: el nombre de las empresas se encuentra en el campo `CUSTOMERNAME`.

In [33]:
# Respuesta 7.1
companies = list(set(sales_data["CUSTOMERNAME"]))
ltd_regexp = r"\bLtd\b"
ltd_companies = [
    company
    for company in companies
    if re.search(ltd_regexp, company) is not None
]

print(ltd_companies)

['Double Decker Gift Stores, Ltd', 'Royal Canadian Collectables, Ltd.', 'Vida Sport, Ltd', 'Corrida Auto Replicas, Ltd', "Men 'R' US Retailers, Ltd.", 'Toms Spezialitten, Ltd', "Anna's Decorations, Ltd", 'Dragon Souveniers, Ltd.', 'Tokyo Collectables, Ltd', 'UK Collectables, Ltd.', 'Signal Collectibles Ltd.', 'Mini Creations Ltd.', 'Mini Gifts Distributors Ltd.', 'Australian Collectables, Ltd']


In [34]:
# Respuesta 7.2
start_end_vowel_regexp = r"^[AEIOUaeiou].*[AEIOUaeiou]$"
s_e_vowel_companies = [
    company
    for company in companies
    if re.match(start_end_vowel_regexp, company)
]
print(s_e_vowel_companies)

['Australian Gift Network, Co', 'Atelier graphique']


## Ejercicio 8

Cread un diccionario ordenado (`OrderedDict`) los elementos del cual sigan la siguiente estructura:

    {
        ORDERID : {
            ORDERPRICE : float,
            ORDERDATE: timestamp,
            STATUS: str,
            PRODUCTLINE: str,
            PRODUCTCODE: str,
            CUSTOMERNAME: str,
            CITY: str,
            COUNTRY: str
        }
    }

La estructura del diccionario sería: {ORDERID_1: {...}, ORDERID_2: {...}, ORDERID_N: {...}}

El diccionario tiene que estar ordenado por *ORDERID* y ha de contener tan sólo las 100 primeras órdenes de *Motorcycles*.

**Pista**: podéis utilizar el método `.to_dict()` de una columna del dataset para convertirla en un diccionario.

<span style="font-family: Courier New; background-color: #82b74b; color: #000000; padding: 3px; ">NM</span> **(1 punto)**

In [35]:
# Respuesta 8
from collections import OrderedDict

sales_data["ORDERDATE"] = pd.to_datetime(
    sales_data["ORDERDATE"], format="%m/%d/%Y %H:%M"
)

mask = sales_data["PRODUCTLINE"] == "Motorcycles"
only_100_motorcycles_sorted = sales_data[mask].sort_values("ORDERID").head(100)
dict_result = only_100_motorcycles_sorted.set_index("ORDERID").to_dict(
    into=OrderedDict, orient="index"
)

print(dict_result)

OrderedDict([(10107, {'ORDERPRICE': 2871.0, 'ORDERDATE': Timestamp('2003-02-24 00:00:00'), 'STATUS': 'Shipped', 'PRODUCTLINE': 'Motorcycles', 'PRODUCTCODE': 'S10_1678', 'CUSTOMERNAME': 'Land of Toys Inc.', 'CITY': 'NYC', 'COUNTRY': 'USA'}), (10120, {'ORDERPRICE': 2793.86, 'ORDERDATE': Timestamp('2003-04-29 00:00:00'), 'STATUS': 'Shipped', 'PRODUCTLINE': 'Motorcycles', 'PRODUCTCODE': 'S10_2016', 'CUSTOMERNAME': 'Australian Collectors, Co.', 'CITY': 'Melbourne', 'COUNTRY': 'Australia'}), (10121, {'ORDERPRICE': 2765.9, 'ORDERDATE': Timestamp('2003-05-07 00:00:00'), 'STATUS': 'Shipped', 'PRODUCTLINE': 'Motorcycles', 'PRODUCTCODE': 'S10_1678', 'CUSTOMERNAME': 'Reims Collectables', 'CITY': 'Reims', 'COUNTRY': 'France'}), (10134, {'ORDERPRICE': 3884.34, 'ORDERDATE': Timestamp('2003-07-01 00:00:00'), 'STATUS': 'Shipped', 'PRODUCTLINE': 'Motorcycles', 'PRODUCTCODE': 'S10_1678', 'CUSTOMERNAME': 'Lyon Souveniers', 'CITY': 'Paris', 'COUNTRY': 'France'}), (10145, {'ORDERPRICE': 3746.7, 'ORDERDATE':

## Ejercicio 9

Definid una **función** que reciba como a parámetro el **diccionario del ejercicio anterior** y:

1. Mostrad por pantalla las órdenes con *STATUS* *Shipped* y que vayan a *USA*.
2. Retornad el *ORDERPRICE* máximo, mínimo y la diferencia entre estos dos valores.

La función ha de estar preparada per trabajar con diccionarios muy grandes. Por tanto, **se ha de evitar guardar los valores individuales mostrados por pantalla en una lista**.

Llamad a la función pasando como parámetro el diccionario del ejercicio anterior.

In [39]:
# Respuesta 9


def shiped_usa(dict_ord):
    max_price = 0.0
    min_price = 0.0
    is_first_it = True

    for k, v in dict_ord.items():
        if v["STATUS"] == "Shipped" and v["COUNTRY"] == "USA":
            print(k)
            if is_first_it:
                max_price = v["ORDERPRICE"]
                min_price = v["ORDERPRICE"]
                is_first_it = False
            else:
                if v["ORDERPRICE"] > max_price:
                    max_price = v["ORDERPRICE"]

                if v["ORDERPRICE"] < min_price:
                    min_price = v["ORDERPRICE"]

    return max_price, min_price, max_price - min_price


shiped_usa(dict_result)

10107
10145
10146
10159
10168
10189
10201
10236
10237
10251
10263
10264
10285
10308
10318
10319
10329
10362
10388


(5205.27, 2168.54, 3036.7300000000005)

## Ejercicio 10

1. Utilizando como información de entrada el diccionario creado en el **ejercicio 8**, calculad en una **única expresión** la media de precios de las órdenes con 'STATUS' 'Shipped' que van a 'Norway' después del 01/01/2003.

2. Utilizando como información de entrada el diccionario creado en el **ejercicio 8**, calculad en una **única expresión** la media de precios de las órdenes con 'STATUS' 'Shipped', 'PRODUCTCODE' 'S10_2016', que van a 'USA' pero no a 'NYC' antes del 01/01/2005.

Recordad que se pueden utilizar librerias científicas para realizar los cálculos de forma sencilla.

In [41]:
# Respuesta 10.1

import numpy as np
import pytz

reference = datetime(year=2003, month=1, day=1)
prices_norway = np.mean(
    [
        v["ORDERPRICE"]
        for k, v in dict_result.items()
        if v["STATUS"] == "Shipped"
        and v["COUNTRY"] == "Norway"
        and v["ORDERDATE"] > reference
    ]
)

print(
    "La media de precios de las órdenes shipped que "
    "van a Norway después del año 2003 es de: {}".format(prices_norway)
)

La media de precios de las órdenes shipped que van a Norway después del año 2003 es de: 3793.786666666667


In [46]:
# Respuesta 10.2

prices_usa = np.mean(
    [
        v["ORDERPRICE"]
        for k, v in dict_result.items()
        if v["STATUS"] == "Shipped"
        and v["PRODUCTCODE"] == "S10_2016"
        and v["COUNTRY"] == "USA"
        and v["CITY"] != "NYC"
        and v["ORDERDATE"] < datetime(year=2005, month=1, day=1)
    ]
)

print(
    "La media de precios de productos shipped con código de "
    "producto S10_2016 que van a USA pero no "
    "a NYC antes del 2005 es: {}".format(prices_usa)
)

La media de precios de productos shipped con código de producto S10_2016 que van a USA pero no a NYC antes del 2005 es: 3448.02
